services:
  - type: web
    name: brainlink-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn brainlink.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: brainlink.settings
