# Generated by Django 5.2.1 on 2025-05-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification_related_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content_object',
        ),
    ]
