# Generated by Django 5.2.1 on 2025-05-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_notification_content_object'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
